return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  event = { 'BufReadPost', 'BufNewFile' },
  opts = {
    ensure_installed = {
      'c',
      'python',
      'bash',
      'lua',
      'sql',
      'make',
      'markdown',
      'vim',
      'vimdoc',
      'html',
      'css',
      'php',
      'cmake',
      'typescript',
      'javascript',
      'cpp',
      'json',
      'yaml',
      'toml',
      'scss',
      'vue',
      'tsx',
      'powershell',
      'go',
      'ruby',
      'nasm',
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
